definitions:
  beer.Allber:
    properties:
      message:
        type: string
    type: object
info:
  contact: {}
paths:
  /beer:
    get:
      description: Get Users
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/beer.Allber'
      summary: Retrieves users from mongodb
swagger: "2.0"
